# export PATH=$HOME/bin:/usr/local/bin:/opt/homebrew/bin:$PATH


# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="powerlevel10k/powerlevel10k"
#ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git rust)

source $ZSH/oh-my-zsh.sh

# User configuration

# ZSH
setopt interactivecomments
bindkey '^[l' down-case-word

# General
LESS='-R -n'
#LESS='-R -n --mouse'
alias ll='ls -alh'
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
source_if_exist() { [[ -s $1 ]] && source $1 || true}

source_if_exist $HOME/.darwin-zshrc
source_if_exist $HOME/.work-zshrc
source_if_exist $HOME/.computer-zshrc

export PATH=$HOME/bin:/usr/local/bin:$PATH

# Ripgrep
#export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

# FZF
source_if_exist $HOME/.fzf.zsh

