########################
#       Oh My ZSH      #
########################

# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

#source $HOME/personal/configuration/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#plugins=(git zsh-syntax-highlighting)
plugins=(git)

source $ZSH/oh-my-zsh.sh

########################
#  User configuration  #
########################

# ZSH
setopt interactivecomments
export PATH=$HOME/.bin/:$HOME/.local/bin:$HOME/.cargo/env:$PATH
bindkey '^[l' down-case-word


# General
LESS='-R -n'
#LESS='-R -n --mouse'
alias ll='ls -alh'
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
source_if_exist() { [[ -s $1 ]] && source $1 }
source_if_exist $HOME/.bash_alias
source_if_exist $HOME/.osx_alias
source_if_exist $HOME/.work_alias
source_if_exist $HOME/.computerrc

# Ripgrep
#export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

# FZF
source_if_exist /usr/share/fzf/key-bindings.zsh  # For linux
source_if_exist /usr/local/opt/fzf/shell/key-bindings.zsh  # For MacOS (old brew)
source_if_exist /opt/homebrew/opt/fzf/shell/key-bindings.zsh  # For MacOS (new brew)
export FZF_COMPLETION_TRIGGER="~~"
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_DEFAULT_OPTS="-e"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fasd -Rdl"
alias fzfag="ag --nobreak --nonumbers --noheading . | fzf-tmux"
_fzf_compgen_path() {
    ag -g "" "$1"
}

if type brew &>/dev/null
then
	FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
	autoload -Uz compinit
	compinit
fi
